### ISSUE TITLE
Finalize business plan

### ISSUE THREAD

**Issue by timeriver** [timeriver/academy#2]
事業計画グーグルスライド版

https://docs.google.com/presentation/d/1aE7_kuYLasu8wEBJ1oRfTqvtEM2G0XZ-n64JisaE4jg/edit#slide=id.p20

バックデータ　スプレッドシート

https://docs.google.com/spreadsheets/d/1m4m-jJyk9LLsgJ3BucHgIY12PoW1JxuL7N2_fRa7QMc/edit#gid=1549100410

**Comment by writerityyuko** [comment]
[Writerity Academy Business plan ver.1.0_20190103.pptx](https://github.com/timeriver/academy/files/2723943/Writerity.Academy.Business.plan.ver.1.0_20190103.pptx)

**Comment by writerityyuko** [comment]
今日時点はこちら。

[Writerity Academy Business plan ver.1.1_20190109.pptx](https://github.com/timeriver/academy/files/2741238/Writerity.Academy.Business.plan.ver.1.1_20190109.pptx)
