### ISSUE TITLE
メイン講師の決定

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/academy#24]

**Comment by writerityyuko** [comment]
@writerity-watanabe 

一人、英語教師として採用したい人物がいます（#11 Vesna)。面接は終了済みで、rWriterity Recruitのスプレッドシートにコメントでメンションしています。
ご確認頂きたく、宜しくお願いします。

https://docs.google.com/spreadsheets/d/1YkPIO9s6wpP-Fugl0n-KbNjCqF9A-vt_grrH3FRveuU/edit#gid=1267053215

**Comment by writerity-watanabe** [comment]
@writerityyuko 
オファーを出すとして、4時間/日スタートでも良さそうな感じでしょうか？
また、10年経験だとかなり給与希望が高そうな気がしますが、その辺りはどうでしょうか？

**Comment by writerityyuko** [comment]
@writerity-watanabe 

4時間だと、オンライン英会話で開講できる時間が少なくなってしまうのですが、それでもよい感じでしょうか？

また、給与希望はあまり高くないと見込んでおります。一応もう一人採用してもよいと思う講師がいるので、もしVesnaさんの給与希望が高額な場合は、2番手に方にオファーする予定です。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
一旦、考えているオファー金額と可能であれば、希望額を教えてください！
良い人材であれば、金額次第で雇用可能です！（フルタイムも

**Comment by writerityyuko** [comment]
@writerity-watanabe 

考えていたオファー案は、以下の通りです。

・時給160MKDで一日6時間（9:00～15:00)/週30時間（会社の諸経費込みのコストは月額約21,300MKD)
・3か月エンゲージメント契約、4か月以降はフルタイム正規雇用の可能性あり
・就業時間内で、第一優先は授業（オンライン予約がある場合）を行い、授業がない時間は、カリキュラム作りの補助
・就業時間外にオンライン英会話の予約がある場合は、別途出来高払い（「副業」としてなら、法定月額最低月給以下でも契約が可能。1コマ（25分）100MKDを想定）
・（ちなみに、メイン講師の就業時間外のコマについては、主にサブの講師（エレナとかボヤンとか）で埋めることを想定。）

でした。
とにかくオンラインを、完全に出来上がってなくても1月中旬に始めることを考えていたので上記を検討していました。

> 例えば、カリキュラム作成費用として最初にまとめてあげて、残りは出来高制など
> 例）
> 1/15雇用、500EURをカリキュラム作成費用として支払い（2/10支払い）
> １名１ヶ月教えたら●●円あげるなど

とにかくカリキュラム（これは、オンラインとインクラス両方と理解していますが）を先に確定させるということであれば、上記のご提案でも可能ですし、そのほうがよいかも・・・と思っていますが、出来高払い（何人いくら、一コマいくら）だと、本人がほかにメインの仕事がない場合は、例の法定最低月給を保証しないといけないので、あまり生徒がつかなかった場合は、無駄なお金が出てしまう可能性があります。（もしくは副業希望の人を募集するか。）

どちらがよいか、迷ってますが、ひとまず、私が考えていたプランをお知らせしておきます。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
> 出来高払い（何人いくら、一コマいくら）だと、本人がほかにメインの仕事がない場合は、例の法定最低月給を保証しないといけない

これは、社員として雇用した場合の話だと思い込んでいましたが、そうではなくフリーランスなどで契約を結んだ際もそうなりますか？

**Comment by writerityyuko** [comment]
@writerity-watanabe 

私の勘違いだったようです。
ボヤンに確認してもらった勘違いをしてたようです。エンゲージメントなら特に関係ないそうです。
失礼しましたー。
取り急ぎ、訂正のみ。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
ありがとうございます！
・カリキュラム（オンライン・インクラス共に）作成の報酬（カリキュラム作成日の翌月10日払い）
・オンライン/インクラス生徒１名が１ヶ月続いた時の報酬（出来高）
＊ここは１ヶ月が良いかなーとは思っていますが、他の方法もありそうなので（そもそも出来高だとオファーを受け入れてくれないかも）、検討お願いします！

**Comment by writerityyuko** [comment]
@Hide 

遅くにご連絡ありがとうございます。承知しました。検討するにあたり、いくつか確認をさせてください。

> ・カリキュラム（オンライン・インクラス共に）作成の報酬（カリキュラム作成日の翌月10日払い）  

**Q1.**カリキュラムの定義ですが、大学で言うシラバス（授業計画）みたいなものをイメージされて言いますか？
それとも、教材そのものをイメージされていますか？

現時点のステータスだと、オンラインもインクラスも、シラバスは大体イメージができているけれども、それに見合う教材が間に合っていない、という現状です。
シラバスの状態から全部見直すという感じでしょうか。

**Q2.**作成は、カリキュラム作成業務を切り出して、完全に委託をする形をお考えでしょうか？
私のこれまでのイメージは、毎日オフィスに来てもらって、こちらが作ったシラバスと教材のイメージを提示して、管理者（渡邊さんとか私とか、あるいは時川さん）の指示の下で教材づくりをしてもらうというイメージでいたのですが、
いわゆる業務委託みたいな形で、仕様書を渡して、納品物に対して報酬を払うイメージでしょうか？

> ・オンライン/インクラス生徒１名が１ヶ月続いた時の報酬（出来高）
> ＊ここは１ヶ月が良いかなーとは思っていますが、他の方法もありそうなので（そもそも出来高だとオファーを受け入れてくれないかも）、検討お願いします！
> 

**Q3.**　具体的にはこんなイメージで感じで合っていますか？
オンラインの場合＝1コマ（25分）の報酬単価（〇〇MKD）×　30日
インクラスの場合＝1コマ（45分）の報酬単価（〇〇MKD）×　120コマ（1か月分）

ちなみに、ご指摘の通り、出来高だと敬遠される可能性はありますね。というか、新たに募集しなおす感じのほうがよいと思いますー。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

> はい！シラバスができているのであれば、全体的な見直し＋見合う教材作成というイメージでしょうか？

はい。そのイメージです。

> どちらでも、こちらとしてはokです！

承知しました。
報酬額と一緒に後ほどご連絡します。少しお待ちください。

> もしカリキュラム作成費用を切り出したりするのであれば、募集内容を変えたほうが良いと思います。

オファーはまだ誰にも出していないので、すでに面接を終えて結果を待ってもらっている候補者には、これから新しくオファーを作って、提示しますね。

**Comment by writerityyuko** [comment]
１）オンラインの教材開発報酬について

結論から言うと、
開講に必要な最低限の教材開発報酬としては、約340€（20,800MKD)、というところかなと思います。

時給200MKDとして、コースA10個、コースB9個の教材を作ってもらうことを想定しました。

コースA（日常会話）の1教材あたりの単価は、時給200MKD×想定作成時間5時間＝1,000MKD
コースB（ビジネス一般）の1教材当たりの単価は、時給200MKD×想定作成時間6時間＝1,200MKD

と設定し、コースA（日常会話）および、コースB（一般ビジネス会話）の両方の教材を作ってもらうとして、

（1,000MKD×コースAの10教材）＋（1,200MKD×コースBの9教材）＝20,8000MKD

と試算しました。

作ってもらう教材のひな型はこちらです。

https://docs.google.com/document/d/1bAWmYedY7fIO6nXHWSRmxMgcCulV3M6ghNOqaChB99M/edit


また、作業内容とアウトプットを指定して、業務委託のような形を想定してみました。

なお、当初、
コースA、コースBともに、よくある場面を10カテゴリー×5オケージョン＝50場面を設定して、それぞれに教材を作ろうと考えていたのですが、合わせて100個の教材を作るのはとても時間がかかりそうなので、最初は10カテゴリーずつ教材を作ることとしました。

どんなカテゴリーなのかは、以前から共有している以下のスプレッドシートの、
onlineカリキュラムのタブをご確認ください。

https://docs.google.com/spreadsheets/d/1m4m-jJyk9LLsgJ3BucHgIY12PoW1JxuL7N2_fRa7QMc/edit#gid=1378828318

２）インクラスの教材開発について

インクラスの授業内容も、上記のスプレッドシートの、
inclassカリキュラムのタブでご確認いただけます。

こちらは基本的にはOxford社の教科書を使って授業を行うのですが、週に何コマか、オリジナルの教材が必要になります。
ただしいくつかのオリジナルの教材はオンラインクラスで作ったものと共有が可能です。
試算は以下の通りです。

(書きかけ。）

**Comment by writerityyuko** [comment]
@writerity-watanabe 

引き続き、講師の給与を出来高にした場合の試算です。

３）オンライン/インクラス生徒１名が１ヶ月続いた時の報酬（出来高）

オンラインクラス授業　コースA
　 @80MKD/1コマ×30回　＝　**2,400 MKD（39ユーロ）**
　1日1回受講と仮定しての試算です。

オンラインクラス授業　コースB
 　@100MKD/1コマ×30回　＝　**3,000MKD（49ユーロ）**
  　1日1回受講と仮定しての試算です。

インクラス授業
 　@160MKD　×6コマ×5日　×4週　＝　**19,200MKD（ 312ユーロ）**

なお、月額給与（あるいは時給×固定日時）で当初募集をかけた理由は、
最初に採用する講師（以下、「メイン講師」）については、
授業（インライン・オンライン）、教材開発、経験の浅い他のオンライン講師のトレーニング、
の3つの業務を、
必要に応じて、いつでも手伝ってもらえるようにと考えていたからだったことを、
念のため追記しておきます。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
> 教材開発費

大体、想像通りの金額なので、良いのではないかと思います。
> 出来高、報酬

承知です！
試算を少し見てみます。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

単純に、給与の額を時給や月給固定ではなく出来高変動にした場合いくらくらいか、ということで試算をしていましたので、
外注扱いはイメージしていませんでした。
つまり、engagement contractの、一つのパターンとして、給与の出来高払いも、できないことはないな、と考えていた次第です。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
おそらく外注扱いもできるかと思いますが、一旦okです！
試算を確認次第、またお伝えします！

**Comment by writerity-watanabe** [comment]
@writerityyuko 
労務英会話の教材でも、依頼できそうなイメージはありますでしょうか？
＊法律などが絡んでくるため

**Comment by writerity-watanabe** [comment]
@writerityyuko 
今週、今日みたいにバタバタしそうなので、一旦スケジュール調整します！

**Comment by writerity-watanabe** [comment]
@writerityyuko 
労務英会話、イメージこんな感じを想定しています。
＊下記、時川より資料共有
また、1/21月の日本時間18時より時川とのミーティングを設定していますので
よろしくお願いします。

▼教材
１、英語
http://hrlibrary.umn.edu/research/Philippines/PD%20442%20-%20Labor%20Code%20of%20the%20Philippines.pdf

２、日本語
https://www.jilaf.or.jp/asia_laborlaw/data/philippine_001.pdf

３、単語リスト
１、２から作成

▼生徒の目標
・法文を正しい発音でスラスラ読める様になる
・単語の意味を理解できる様になる

**Comment by writerityyuko** [comment]
@writerity-watanabe 

> また、1/21月の日本時間18時より時川とのミーティングを設定していますので

承知しました。ご調整ありがとうございます。

> 労務英会話、イメージこんな感じで想定しています。
> ▼生徒の目標
> ・法文を正しい発音でスラスラ読める様になる
> ・単語の意味を理解できる様になる

以前、エレナに指示を出していたイメージですかね？
どちらかというと、時川さんが希望されているコースは、労務英会話というよりは、
「労働法読解」、という感じなのですね。
承知しました。
