### ISSUE TITLE
Writerity Academyのウェブサイト参考サイト選び

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/academy#37]
イケサイ

https://www.ikesai.com/

**Comment by writerityyuko** [comment]
構造はこんな感じがよい。

http://www.hi-c.co.jp/

すっきりしててよい。

http://fitac.jp/

**Comment by writerityyuko** [comment]
こっちのほうがかっこいいかも。

https://www.stgiles-international.com/english-language-schools/usa/new-york

**Comment by writerityyuko** [comment]
あるいはこっち。

https://thepacklanguageexperience.com/language-courses-abroad/

**Comment by writerity-watanabe** [comment]
@writerityyuko 
ちなみに、サイトのメインとなる色については、ここから見つけられるかもしれません。
https://www.colordic.org/
https://www.colordic.org/picker/

＊濃いブルー、賛成です。
＊ライタリティのウェブサイトもそれに合わせて色変更（デザイン含め）したいなーと思いつつあります。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

ありがとうございます。見てみますー。
また、今、自分のメモ的にいろいろサイトを張り付けてますが、
絞り込んで、改めてお知らせしなおしますね。

> ＊濃いブルー、賛成です。

よかったです。なぜか、私、昔から、紺色がすごく落ち着くんですよ。

> ＊ライタリティのウェブサイトもそれに合わせて色変更（デザイン含め）したいなーと思いつつあります。

そうですね。コーポレートカラーを決めて、
事業ごとにちょっと色味を変えてページを作るとかしたらいいのかもしれませんね。
でもJovicaが作り直しているページは、緑がベースですよね。
緑も、クリーンな感じがしていいなと思いました。

**Comment by writerityyuko** [comment]
これもみやすい。

https://learnenglish.britishcouncil.org/

**Comment by writerityyuko** [comment]
@writerity-watanabe

Writerity Academyの参考サイトですが、以下の3つをピックアップしてみましたが、渡邊さんが違和感なければ、これを時川さんに投げようかと思っています。

ちなみに、アカデミーの件で時川さんにご連絡する際は、スカイプがいいのでしょうか？それともこのGithubのプロジェクト上でメンションする形がよいのでしょうか？

▼N高等学校
https://nnn.ed.jp/

→こちらのサイトはよく整理されていて、すっきりと洗練されている感じを参考にしたい。

▼St.Giles International
https://www.stgiles-international.com/english-language-schools/usa/new-york

→おしゃれな感じもするし、学校の雰囲気も伝わりやすい感じを参考にしたい。色の組み合わせもこの紺色、茶色、赤（ピンク）の組み合わせが良い感じ。

▽色パターンについては、いかの2つのうちどちらかはいかがでしょうか。

https://www.colourlovers.com/palette/2826404/P_r_i_s_m

https://www.colourlovers.com/palette/347848/El_Encanto

**Comment by writerity-watanabe** [comment]
@writerityyuko 
こちらですが、時川さんの別アカウントが入っていないので少々お待ちください。
今回は、チャットワークもしくスカイプで投げても問題ないです！

サイト・色の組み合わせについても違和感ありません。
色については、個人的には上の方が良いかなーという印象はあります！
