### ISSUE TITLE
スケジュール調整

### ISSUE THREAD

**Issue by writerity-watanabe** [timeriver/academy#7]

**Comment by writerity-watanabe** [comment]
@writerityyuko 
オンラインコース、
コース費用などが確定し、ある程度内容も固まり次第すぐに始めてしまおうと思いますのでスケジュール立てましょう！

**Comment by writerityyuko** [comment]
@writerityyuko 

はい。承知しました。

**Comment by writerityyuko** [comment]
12月11日（火）13:00から打ち合わせ。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
優先で進めましょう！（SAC業務が最優先）
＊その他、ライタリティ内で期限あるタスクあれば教えてください！
また打ち合わせ、MAX30分で考えています。
＊一応13時から１時間は空けておきますが

**Comment by writerityyuko** [comment]
@writerityyuko 

期限のあるものは特になかったと思いますが、

・SAC業務（デザイナーチェック、日本人採用進捗管理）
・ライタリティアカデミー
・ライタリティHRの進捗管理

「以外」のものは、当分手が回らないと思われます。。。

3つ目のライタリティHRも怪しいけど、
ボヤン2号に仕事振りまくってなんとかしのごうと思ってます。

はい。30分で済ませましょう。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
問題ないです！
```
ライタリティHRの進捗管理
```
１ヶ月で手を離れられると良いかと思います。
基本、Bojan２号が全て対応（DimitarやJovica/Kireとのやり取り含め）→渡邊の承認のみで完結したいです。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

はーい。そうなるといいなーと私も思います。

実はデザイナーのチェックもSACの皆様が来マケドニアされるまでの1か月のリリーフピッチャーなので、
この1か月が過ぎると、実はすごく楽になれるのかもしれません、私。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
そうですね、その後は
完全に新規事業に注力していただきたいと思っていますので、逆に大変になったりするかもしれませんが、よろしくお願いします。

その他、やりたい業務等あればぜひ教えていただけると！
ちなみに、年末年始の予定決まり次第お願いします！

**Comment by writerityyuko** [comment]
@writerity-watanabe 

やりたい業務ですか。あるっちゃあるんですが、
考えておきます。

は！そうだ。冬休み！
夫を捕まえて話をします！

**Comment by writerity-watanabe** [comment]
@writerityyuko 
売上を建てられるような業務であれば尚良しです！
＊給与アップの可能性も広がります
＊例えば、システム開発のプロジェクト管理など。。

エレナも特に休まない（1/1は祝日で休み）ようなので、働く分には構いません。
